# Cargar datos y librerias

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Basic
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from statistics import mode
import os
import glob
import random
import cv2

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from scipy.sparse import coo_matrix
from sklearn.utils import shuffle

import cv2
# Features 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.decomposition import PCA
from skimage import feature
# Metrics 
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score #c alculate accuracy
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import plot_confusion_matrix
# Classifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn import svm
#Save model
import joblib  

# Carga de datos 1

In [ ]:
path = "/content/drive/MyDrive/Colab Notebooks/Base-De-Datos/datasetVGG/1-African American/train"

list_people = os.listdir(path)

type_file = "*.jpg"

cont = 0
cont2 = 0

for k in list_people:
    
    path_image = path + "/" + k
    list_jpg = glob.glob(path_image + os.sep + type_file)
    
    cont += len(list_jpg)
    
print("El número de muestras: ",cont)

train_data = np.zeros((cont,168*192*2))
train_data = train_data.astype('float32')

y_train = np.zeros(cont)
y_train = y_train.astype('int8')


for i in list_people:
    
    #print(i)
    
    path_image = path + "/" + i
    
    list_jpg = glob.glob(path_image + os.sep + type_file)
    
    for j in list_jpg:
        
        image = cv2.imread(j, cv2.IMREAD_COLOR)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
        image = cv2.resize(image, (168,192))
        H,S,V = cv2.split(image)
        image_merge = np.zeros((192,168,2))
        image_merge[:,:,0] = S
        image_merge[:,:,1] = V
        image_merge = image_merge.ravel()
        train_data[cont2] += image_merge 

        y_train[cont2] = i[-2] + i[-1]

        #print(y_train[cont2])
        cont2 += 1

#print(y_train)

El número de muestras:  2593


In [ ]:
path = "/content/drive/MyDrive/Colab Notebooks/Base-De-Datos/datasetVGG/1-African American/test"

list_people = os.listdir(path)

subcadena = "yaleB" #la subcadena que queremos localizar
type_file = "*.jpg"

cont = 0
cont2 = 0

for k in list_people:
    
    path_image = path + "/" + k
    list_jpg = glob.glob(path_image + os.sep + type_file)
    
    cont += len(list_jpg)
    
print("El número de muestras: ",cont)

test_data = np.zeros((cont,168*192*2))
test_data = test_data.astype('float32')

y_test = np.zeros(cont)
y_test = y_test.astype('int8')


for i in list_people:
    
    #print(i)
    
    path_image = path + "/" + i
    
    list_jpg = glob.glob(path_image + os.sep + type_file)
    
    for j in list_jpg:
        
        image = cv2.imread(j, cv2.IMREAD_COLOR)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
        image = cv2.resize(image, (168,192))
        H,S,V = cv2.split(image)
        image_merge = np.zeros((192,168,2))
        image_merge[:,:,0] = S
        image_merge[:,:,1] = V
        image_merge = image_merge.ravel()

        test_data[cont2] += image_merge 

        y_test[cont2] = i[-2] + i[-1]
        #print(y_train[cont2])
        cont2 += 1

#print(y_train)

El número de muestras:  1000


#Test

In [ ]:
#image = cv2.imread("/content/drive/MyDrive/Colab Notebooks/Base-De-Datos/datasetVGG/1-African American/train/african_001/0001_02.jpg", cv2.IMREAD_COLOR)

In [ ]:
#image = cv2.resize(image, (168,192))
#H,S,V = cv2.split(image)
#S.shape

(192, 168)

In [ ]:
#image_merge = np.zeros((192,168,2))

#image_merge[:,:,0] = S
#image_merge[:,:,1] = V

In [ ]:
#print(V)

[[232 232 229 ... 155 150 149]
 [231 230 228 ... 159 154 153]
 [228 227 225 ... 168 164 163]
 ...
 [ 83  83  80 ...  81  82  82]
 [ 83  83  80 ...  81  81  81]
 [ 83  82  80 ...  81  81  81]]


In [ ]:
#print(image_merge[:,:,1])

[[232. 232. 229. ... 155. 150. 149.]
 [231. 230. 228. ... 159. 154. 153.]
 [228. 227. 225. ... 168. 164. 163.]
 ...
 [ 83.  83.  80. ...  81.  82.  82.]
 [ 83.  83.  80. ...  81.  81.  81.]
 [ 83.  82.  80. ...  81.  81.  81.]]


In [ ]:
#train_data, y_train = extract_data(path_train,"*.jpg",True)

In [ ]:
#test_data, y_test = extract_data(path_test,"*.jpg",True)

In [ ]:
#import sys
#np.set_printoptions(threshold=sys.maxsize)
#y_train

# Separar datos en train y test

In [ ]:
#nsamples, nx, ny, chanels = train_data.shape

#train_data = train_data.reshape((nsamples,nx*ny*chanels))

X_sparse = coo_matrix(train_data)

train_data, X_sparse, y_train = shuffle(train_data, X_sparse,y_train, random_state=0)

#train_data = train_data.reshape((nsamples,nx,ny,chanels))

In [ ]:
#nsamples, nx, ny, chanels = test_data.shape

#test_data = test_data.reshape((nsamples,nx*ny*chanels))

X_sparse = coo_matrix(test_data)

test_data, X_sparse, y_test = shuffle(test_data, X_sparse,y_test, random_state=0)

#test_data = test_data.reshape((nsamples,nx,ny,chanels))

In [ ]:
train_data = train_data.astype("uint8")
#nsamples1, nx1, ny1, chanels = train_data.shape
#train_data = train_data.reshape((nsamples1,nx1*ny1*chanels))
train_data = train_data/255

test_data = test_data.astype("uint8")
#nsamples, nx, ny, chanels = test_data.shape
#test_data = test_data.reshape((nsamples,nx*ny*chanels))
test_data = test_data/255

# PCA 

## Extracción de caracteristicas 

In [ ]:
n_components = 150

print("Extrayendo %d eigenfaces de %d caras"
      % (n_components, train_data.shape[0]))

pca = PCA(n_components=n_components, svd_solver='randomized',
          whiten=True).fit(train_data)


#eigenfaces = pca.components_.reshape((n_components,192, 162))

print("Projecting the input data on the eigenfaces orthonormal basis")

train_data_pca = pca.transform(train_data)
test_data_pca = pca.transform(test_data)

Extrayendo 150 eigenfaces de 2593 caras
Projecting the input data on the eigenfaces orthonormal basis


texto en negrita## SVM


## SVM

In [ ]:
from sklearn.model_selection import GridSearchCV


param_grid = {'C': [1e3, 5e3, 1e4, 5e4, 1e5],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.1], }

clf_pca_svm = GridSearchCV(
    SVC(kernel='rbf', class_weight='balanced'), param_grid
)
clf_pca_svm = clf_pca_svm.fit(train_data_pca,y_train )

print("Best estimator found by grid search:")
print(clf_pca_svm.best_estimator_)

Best estimator found by grid search:
SVC(C=1000.0, class_weight='balanced', gamma=0.005)


In [ ]:
y_pred = clf_pca_svm.predict(test_data_pca)

print(classification_report(y_test, y_pred,digits=4))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           1     0.7843    0.8000    0.7921        50
           2     0.7895    0.9000    0.8411        50
           3     0.9200    0.9200    0.9200        50
           4     0.7778    0.8400    0.8077        50
           5     0.7778    0.8400    0.8077        50
           6     0.7018    0.8000    0.7477        50
           7     0.5686    0.5800    0.5743        50
           8     0.8298    0.7800    0.8041        50
           9     0.7917    0.7600    0.7755        50
          10     0.6607    0.7400    0.6981        50
          11     0.8333    0.6000    0.6977        50
          12     1.0000    1.0000    1.0000        50
          13     0.8800    0.8800    0.8800        50
          14     0.9130    0.8400    0.8750        50
          15     0.6226    0.6600    0.6408        50
          16     0.7959    0.7800    0.7879        50
          17     0.8000    0.6400    0.7111        50
          18     0.8810    

## knn

In [ ]:
clf_PCA_Knn_3 = KNeighborsClassifier(n_neighbors=3)

In [ ]:
clf_lbp_Kn_3 = clf_PCA_Knn_3.fit(train_data_pca,y_train)

In [ ]:
y_pred = clf_PCA_Knn_3.predict(test_data_pca)

print(classification_report(y_test, y_pred,digits=4))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           1     0.3333    0.5600    0.4179        50
           2     0.2118    0.8600    0.3399        50
           3     0.4667    0.7000    0.5600        50
           4     0.3898    0.4600    0.4220        50
           5     0.7619    0.3200    0.4507        50
           6     0.4571    0.3200    0.3765        50
           7     0.3095    0.2600    0.2826        50
           8     0.5476    0.4600    0.5000        50
           9     0.2083    0.6000    0.3093        50
          10     0.7333    0.2200    0.3385        50
          11     0.5500    0.2200    0.3143        50
          12     0.9444    0.6800    0.7907        50
          13     0.8636    0.3800    0.5278        50
          14     0.8438    0.5400    0.6585        50
          15     0.5714    0.0800    0.1404        50
          16     0.2870    0.6200    0.3924        50
          17     1.0000    0.3000    0.4615        50
          18     1.0000    

## Gauss

In [ ]:
clf_PCA_Gauss = GaussianNB()

In [ ]:
clf_lbp_Gauss = clf_PCA_Gauss.fit(train_data_pca,y_train)

In [ ]:
y_pred = clf_lbp_Gauss.predict(test_data_pca)

print(classification_report(y_test, y_pred,digits=4))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           1     0.6667    0.5600    0.6087        50
           2     0.3925    0.8400    0.5350        50
           3     0.8627    0.8800    0.8713        50
           4     0.6333    0.3800    0.4750        50
           5     0.6122    0.6000    0.6061        50
           6     0.5625    0.3600    0.4390        50
           7     0.5641    0.4400    0.4944        50
           8     0.7333    0.6600    0.6947        50
           9     0.3535    0.7000    0.4698        50
          10     0.5128    0.4000    0.4494        50
          11     0.8261    0.3800    0.5205        50
          12     0.9524    0.8000    0.8696        50
          13     0.8889    0.8000    0.8421        50
          14     0.9000    0.7200    0.8000        50
          15     0.3065    0.3800    0.3393        50
          16     0.4138    0.7200    0.5255        50
          17     0.6512    0.5600    0.6022        50
          18     0.8621    

# LDA

## Extracción de caracteristicas 

In [ ]:
lda = LDA(n_components=19)
X_train = lda.fit_transform(train_data, y_train)
train_data_LDA = lda.transform(train_data)
test_data_LDA = lda.transform(test_data)

## SVM

In [ ]:
clf_lda_svm = GridSearchCV(
    SVC(kernel='rbf', class_weight='balanced'), param_grid
)
clf_lda_svm = clf_lda_svm.fit(train_data_LDA,y_train )

print("Best estimator found by grid search:")
print(clf_lda_svm.best_estimator_)

Best estimator found by grid search:
SVC(C=1000.0, class_weight='balanced', gamma=0.01)


In [ ]:
y_pred_lda_svm = clf_lda_svm.predict(test_data_LDA)

print(classification_report(y_test, y_pred_lda_svm,digits=4))

              precision    recall  f1-score   support

           1     0.5714    0.3200    0.4103        50
           2     0.3214    0.7200    0.4444        50
           3     0.6981    0.7400    0.7184        50
           4     0.4286    0.3000    0.3529        50
           5     0.9545    0.4200    0.5833        50
           6     0.5294    0.3600    0.4286        50
           7     0.2963    0.1600    0.2078        50
           8     0.6522    0.6000    0.6250        50
           9     0.1582    0.5600    0.2467        50
          10     0.5000    0.4400    0.4681        50
          11     0.5833    0.1400    0.2258        50
          12     0.8364    0.9200    0.8762        50
          13     0.8636    0.7600    0.8085        50
          14     0.6500    0.7800    0.7091        50
          15     0.4800    0.2400    0.3200        50
          16     0.3500    0.5600    0.4308        50
          17     0.6429    0.3600    0.4615        50
          18     0.7174    

## knn

In [ ]:
clf_LDA_Knn_3 = KNeighborsClassifier(n_neighbors=3)

In [ ]:
clf_LDA_Knn_3 = clf_PCA_Knn_3.fit(train_data_LDA,y_train)

In [ ]:
y_pred = clf_LDA_Knn_3.predict(test_data_LDA)

print(classification_report(y_test, y_pred,digits=4))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           1     0.5667    0.6800    0.6182        50
           2     0.5000    0.7000    0.5833        50
           3     0.6552    0.7600    0.7037        50
           4     0.5000    0.5000    0.5000        50
           5     0.8182    0.7200    0.7660        50
           6     0.4348    0.6000    0.5042        50
           7     0.3182    0.4200    0.3621        50
           8     0.7500    0.6600    0.7021        50
           9     0.5636    0.6200    0.5905        50
          10     0.4800    0.4800    0.4800        50
          11     0.6000    0.3600    0.4500        50
          12     0.8868    0.9400    0.9126        50
          13     0.8542    0.8200    0.8367        50
          14     0.7400    0.7400    0.7400        50
          15     0.3617    0.3400    0.3505        50
          16     0.6286    0.4400    0.5176        50
          17     0.8214    0.4600    0.5897        50
          18     0.8293    

## Gauss

In [ ]:
clf_LDA_Gauss = GaussianNB()

In [ ]:
clf_LDA_Gauss = clf_LDA_Gauss.fit(train_data_LDA,y_train)

In [ ]:
y_pred = clf_LDA_Gauss.predict(test_data_LDA)

print(classification_report(y_test, y_pred,digits=4))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           1     0.8333    0.2000    0.3226        50
           2     0.1752    0.8200    0.2887        50
           3     0.9655    0.5600    0.7089        50
           4     0.7000    0.2800    0.4000        50
           5     1.0000    0.4000    0.5714        50
           6     0.8333    0.3000    0.4412        50
           7     0.3571    0.1000    0.1562        50
           8     0.8462    0.6600    0.7416        50
           9     0.2155    0.7800    0.3377        50
          10     0.3913    0.5400    0.4538        50
          11     1.0000    0.0400    0.0769        50
          12     0.8800    0.8800    0.8800        50
          13     0.9444    0.6800    0.7907        50
          14     0.8537    0.7000    0.7692        50
          15     0.5833    0.1400    0.2258        50
          16     0.2857    0.6400    0.3951        50
          17     0.8182    0.1800    0.2951        50
          18     0.8889    

# Carga de datos 2

In [ ]:
path = "/content/drive/MyDrive/Colab Notebooks/Base-De-Datos/datasetVGG/1-African American/train"

list_people = os.listdir(path)

type_file = "*.jpg"

cont = 0
cont2 = 0

for k in list_people:
    
    path_image = path + "/" + k
    list_jpg = glob.glob(path_image + os.sep + type_file)
    
    cont += len(list_jpg)
    
print("El número de muestras: ",cont)

train_data = np.zeros((cont,192,168,2))
train_data = train_data.astype('float32')

y_train = np.zeros(cont)
y_train = y_train.astype('int8')


for i in list_people:
    
    #print(i)
    
    path_image = path + "/" + i
    
    list_jpg = glob.glob(path_image + os.sep + type_file)
    
    for j in list_jpg:
        
        image = cv2.imread(j, cv2.IMREAD_COLOR)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
        image = cv2.resize(image, (168,192))
        H,S,V = cv2.split(image)
        image_merge = np.zeros((192,168,2))
        image_merge[:,:,0] = S
        image_merge[:,:,1] = V
        train_data[cont2] += image_merge 

        y_train[cont2] = i[-2] + i[-1]

        #print(y_train[cont2])
        cont2 += 1

#print(y_train)

El número de muestras:  2593


In [ ]:
path = "/content/drive/MyDrive/Colab Notebooks/Base-De-Datos/datasetVGG/1-African American/test"

list_people = os.listdir(path)

subcadena = "yaleB" #la subcadena que queremos localizar
type_file = "*.jpg"

cont = 0
cont2 = 0

for k in list_people:
    
    path_image = path + "/" + k
    list_jpg = glob.glob(path_image + os.sep + type_file)
    
    cont += len(list_jpg)
    
print("El número de muestras: ",cont)

test_data = np.zeros((cont,192,168,2))
test_data = test_data.astype('float32')

y_test = np.zeros(cont)
y_test = y_test.astype('int8')


for i in list_people:
    
    #print(i)
    
    path_image = path + "/" + i
    
    list_jpg = glob.glob(path_image + os.sep + type_file)
    
    for j in list_jpg:
        
        image = cv2.imread(j, cv2.IMREAD_COLOR)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
        image = cv2.resize(image, (168,192))
        H,S,V = cv2.split(image)
        image_merge = np.zeros((192,168,2))
        image_merge[:,:,0] = S
        image_merge[:,:,1] = V
        

        test_data[cont2] += image_merge 

        y_test[cont2] = i[-2] + i[-1]
        #print(y_train[cont2])
        cont2 += 1

#print(y_train)

El número de muestras:  1000


# Separar datos en train y test

In [ ]:
nsamples, nx, ny, chanels = train_data.shape

train_data = train_data.reshape((nsamples,nx*ny*chanels))

X_sparse = coo_matrix(train_data)

train_data, X_sparse, y_train = shuffle(train_data, X_sparse,y_train, random_state=0)

train_data = train_data.reshape((nsamples,nx,ny,chanels))

In [ ]:
nsamples, nx, ny, chanels = test_data.shape

test_data = test_data.reshape((nsamples,nx*ny*chanels))

X_sparse = coo_matrix(test_data)

test_data, X_sparse, y_test = shuffle(test_data, X_sparse,y_test, random_state=0)

test_data = test_data.reshape((nsamples,nx,ny,chanels))

In [ ]:
train_data = train_data.astype("uint8")
nsamples1, nx1, ny1, chanels = train_data.shape
train_data = train_data.reshape((nsamples1,nx1*ny1*chanels))
train_data = train_data/255

test_data = test_data.astype("uint8")
nsamples, nx, ny, chanels = test_data.shape
test_data = test_data.reshape((nsamples,nx*ny*chanels))
test_data = test_data/255

In [ ]:
train_data = train_data.reshape((nsamples1,nx1,ny1,chanels))
test_data = test_data.reshape((nsamples,nx,ny,chanels))

In [ ]:
train_data_S = np.zeros((nsamples1,192,168))
train_data_S = train_data[:,:,:,0]
train_data_V = np.zeros((nsamples1,192,168))
train_data_V = train_data[:,:,:,1]

test_data_S = np.zeros((nsamples,192,168))
test_data_S = test_data[:,:,:,0]
test_data_V = np.zeros((nsamples1,192,168))
test_data_V = test_data[:,:,:,1]

# LBP


## Extracción de caracteristicas

In [ ]:
# https://github.com/AsoStrife/Computer-Vision-Project

def blockshaped(arr, nrows, ncols):

    h, w = arr.shape
    return (arr.reshape(h//nrows, nrows, -1, ncols)
            .swapaxes(1,2)
            .reshape(-1, nrows, ncols))
def getHistogram(imgArray):
    hist, bin_edges = np.histogram(imgArray, density=True)
    return hist

In [ ]:
# tamaño de train y test
cont_train = train_data.shape[0]
cont_test = test_data.shape[0]
print(cont_test)

1000


In [ ]:
#train_data_LBP = train_data.reshape((cont_train,nx,ny))
lbp_feactures  = np.zeros((cont_train,nx,ny))

eps = 1e-7
radius = 1
n_points = 8 * radius

lbp_hist_S = np.zeros((cont_train,1440))

for i in range(0,cont_train): 
    lbp = feature.local_binary_pattern(train_data_S[i], n_points, radius)
    lbp_feactures[i] +=  lbp
    
    shaped = blockshaped(lbp_feactures[i], 16, 14)
    x = []
    xBlocks = []
    for s in shaped:
        xBlocks.append(getHistogram(s))
    # Concatenate the various histogram, the resulting histogram is append into feature vector
    x.append(np.concatenate(xBlocks))
    
    lbp_hist_S[i] += x[0]

In [ ]:
#train_data_LBP = train_data.reshape((cont_train,nx,ny))
lbp_feactures  = np.zeros((cont_train,nx,ny))

eps = 1e-7
radius = 1
n_points = 8 * radius

lbp_hist_V = np.zeros((cont_train,1440))

for i in range(0,cont_train): 
    lbp = feature.local_binary_pattern(train_data_V[i], n_points, radius)
    lbp_feactures[i] +=  lbp
    
    shaped = blockshaped(lbp_feactures[i], 16, 14)
    x = []
    xBlocks = []
    for s in shaped:
        xBlocks.append(getHistogram(s))
    # Concatenate the various histogram, the resulting histogram is append into feature vector
    x.append(np.concatenate(xBlocks))
    
    lbp_hist_V[i] += x[0]

In [ ]:
#test_data_LBP = test_data.reshape((cont_test,nx,ny))
lbp_feactures_test  = np.zeros((cont_test,nx,ny))


lbp_hist_test_S = np.zeros((cont_test,1440))

for i in range(0,cont_test): 
    lbp = feature.local_binary_pattern(test_data_S[i], n_points, radius)
    lbp_feactures_test[i] +=  lbp
    
    shaped = blockshaped(lbp_feactures_test[i], 16, 14)
    x = []
    xBlocks = []
    for s in shaped:
        xBlocks.append(getHistogram(s))
    # Concatenate the various histogram, the resulting histogram is append into feature vector
    x.append(np.concatenate(xBlocks))
    
    lbp_hist_test_S[i] += x[0]
    

In [ ]:
#test_data_LBP = test_data.reshape((cont_test,nx,ny))
lbp_feactures_test  = np.zeros((cont_test,nx,ny))


lbp_hist_test_V = np.zeros((cont_test,1440))

for i in range(0,cont_test): 
    lbp = feature.local_binary_pattern(test_data_V[i], n_points, radius)
    lbp_feactures_test[i] +=  lbp
    
    shaped = blockshaped(lbp_feactures_test[i], 16, 14)
    x = []
    xBlocks = []
    for s in shaped:
        xBlocks.append(getHistogram(s))
    # Concatenate the various histogram, the resulting histogram is append into feature vector
    x.append(np.concatenate(xBlocks))
    
    lbp_hist_test_V[i] += x[0]
    

In [ ]:
lbp_hist_test_V.shape

(1000, 1440)

In [ ]:
lbp_hist = np.concatenate((lbp_hist_S,lbp_hist_V),axis=1)
lbp_hist.shape

(2593, 2880)

In [ ]:
lbp_hist_test = np.concatenate((lbp_hist_test_S,lbp_hist_test_V),axis=1)
lbp_hist_test.shape

(1000, 2880)

## SMV

In [ ]:
param_grid = {'C': [1e3, 5e3, 1e4, 5e4, 1e5],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.1], }
clf_lbp_svm = GridSearchCV(
    SVC(kernel='rbf', class_weight='balanced'), param_grid
)
clf_lbp_svm = clf_lbp_svm.fit(lbp_hist,y_train )

print("El mejor conjunto de caracteriticas es: ")
print(clf_lbp_svm.best_estimator_)

El mejor conjunto de caracteriticas es: 
SVC(C=5000.0, class_weight='balanced', gamma=0.1)


In [ ]:
y_pred_lbp_svm = clf_lbp_svm.predict(lbp_hist_test)

print(classification_report(y_test, y_pred_lbp_svm,digits=4))

              precision    recall  f1-score   support

           1     0.9111    0.8200    0.8632        50
           2     0.8571    0.8400    0.8485        50
           3     0.8431    0.8600    0.8515        50
           4     0.8333    0.7000    0.7609        50
           5     0.7778    0.7000    0.7368        50
           6     0.6271    0.7400    0.6789        50
           7     0.7308    0.7600    0.7451        50
           8     0.8636    0.7600    0.8085        50
           9     0.9091    0.8000    0.8511        50
          10     0.6727    0.7400    0.7048        50
          11     0.9500    0.7600    0.8444        50
          12     0.9375    0.9000    0.9184        50
          13     0.9268    0.7600    0.8352        50
          14     0.9149    0.8600    0.8866        50
          15     0.7317    0.6000    0.6593        50
          16     0.8077    0.8400    0.8235        50
          17     0.3936    0.7400    0.5139        50
          18     0.8302    

## KNN

In [ ]:
clf_lbp_Kn_3 = KNeighborsClassifier(n_neighbors=7)

In [ ]:
clf_lbp_Kn_3 = clf_lbp_Kn_3.fit(lbp_hist,y_train)

In [ ]:
y_pred_lbp_knn = clf_lbp_Kn_3.predict(lbp_hist_test)

print(classification_report(y_test, y_pred_lbp_knn,digits=4))

              precision    recall  f1-score   support

           1     0.3977    0.7000    0.5072        50
           2     0.5000    0.7200    0.5902        50
           3     0.5125    0.8200    0.6308        50
           4     0.4386    0.5000    0.4673        50
           5     0.5778    0.5200    0.5474        50
           6     0.6207    0.3600    0.4557        50
           7     0.5000    0.5000    0.5000        50
           8     0.7083    0.6800    0.6939        50
           9     0.6216    0.4600    0.5287        50
          10     0.8125    0.2600    0.3939        50
          11     0.5645    0.7000    0.6250        50
          12     0.8140    0.7000    0.7527        50
          13     0.7692    0.6000    0.6742        50
          14     0.5116    0.8800    0.6471        50
          15     0.6250    0.3000    0.4054        50
          16     0.4167    0.4000    0.4082        50
          17     0.7000    0.4200    0.5250        50
          18     0.8333    

## Gauss

In [ ]:
clf_lbp_Gauss = GaussianNB()

In [ ]:
clf_lbp_Gauss = clf_lbp_Gauss.fit(lbp_hist,y_train)

In [ ]:
y_pred_lbp_knn = clf_lbp_Gauss.predict(lbp_hist_test)

print(classification_report(y_test, y_pred_lbp_knn,digits=4))

              precision    recall  f1-score   support

           1     0.4746    0.5600    0.5138        50
           2     0.2500    0.5000    0.3333        50
           3     0.5147    0.7000    0.5932        50
           4     0.4828    0.2800    0.3544        50
           5     0.3333    0.0600    0.1017        50
           6     0.2000    0.0600    0.0923        50
           7     0.1429    0.0200    0.0351        50
           8     0.3846    0.4000    0.3922        50
           9     0.3077    0.0800    0.1270        50
          10     0.2632    0.4000    0.3175        50
          11     0.0000    0.0000    0.0000        50
          12     0.6429    0.5400    0.5870        50
          13     0.5000    0.1600    0.2424        50
          14     0.5082    0.6200    0.5586        50
          15     0.1786    0.2000    0.1887        50
          16     0.1801    0.5800    0.2749        50
          17     0.3500    0.5600    0.4308        50
          18     0.5091    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
